
SIMULATION = False

FSM_UPDATE_RATE_SEC = 0.25
ACCLRMTR_LIVE_VIEW_RATE_SEC = 0.1
ACCLRMTR_LIVE_VIEW_NUM_SAMPLES = 200
ACCLRMTR_LIVE_VIEW_DOWNSAMPLE_FACTOR = 8

MOVE_TO_CENTER_SPEED_MM_PER_MIN = 6000

FSM_SWEEP_START_DLY = 0.5

TMP_PARAM_SWEEP_f0 = 7.
TMP_PARAM_SWEEP_f1 = 87.
TMP_PARAM_SWEEP_dfdt = 4.
TMP_PARAM_SWEEP_A = 4000.

T_DFLT = 1./1600.    # Default sample time to use (accelerometer sample time).

MAX_RETRIES_FOR_MISSED_SAMPLES = 2
GET_AXIS_INFO_TIMEOUT = 10.
CENTER_AXIS_TIMEOUT = 12.

SERVICE_URL = 'https://voo99nz0i7.execute-api.us-east-2.amazonaws.com/Dev/CaaS'
SERVICE_TIMEOUT_THD = 15
